package com.witcurve.domain.enumeration;

public enum AttachmentType {

    STUDENT_IMPORT, STAFF_IMPORT, INSTITUTE_LOGO, STAFF_PAYROLL, STUDENT_REPORT, STANDARD_REPORT, STANDARD_REPORT_WITHOUT_HEADER, FEE_PAYMENT_RECORD, STUDENT_PROFILE_PHOTO, STAFF_PROFILE_PHOTO, ALBUM_PHOTO
}
